### PR TITLE
Avoid duplicate testing during coverage

### PR DESCRIPTION
**Pull request by cworth-gh**
See card and individual commit messages for details.

### CODE REVIEW

**Comment by cworth-gh** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;opyiNwBe&#x2F;175-nifty-should-run-test-suite-only-once-0-5"> nifty should run test suite only once [0.5]</a>

**Comment by mliudev** [comment]
Had a comment on the first commit.

**Comment by ericamador** [comment]
This looks great. :+1:

**Comment by mliudev** [comment]
Looks good.

**Pull request merged**
